version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fugue-crawler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r5ohfgher3qz"
s3_prefix = "metty"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = [
  "Scraper=078053134682.dkr.ecr.eu-west-1.amazonaws.com/lambdas",
]